use omx_config::OmxConfig;
use omx_types::OmxError;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum SetupScope {
    User,
    Project,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentDefinition {
    pub name: String,
    pub description: String,
    pub model: Option<String>,
    pub tools: Vec<String>,
}

pub trait SetupGenerator: Send + Sync {
    fn generate_config_toml(
        &self,
        config: &OmxConfig,
        scope: SetupScope,
    ) -> Result<String, OmxError>;

    fn generate_agents_md(&self, config: &OmxConfig) -> Result<String, OmxError>;

    fn generate_agent_tomls(
        &self,
        agents: &[AgentDefinition],
    ) -> Result<Vec<(String, String)>, OmxError>;

    fn sync_mcp_servers(&self, config: &OmxConfig, scope: SetupScope) -> Result<(), OmxError>;

    fn copy_prompts(&self, scope: SetupScope) -> Result<(), OmxError>;

    fn copy_skills(&self, scope: SetupScope) -> Result<(), OmxError>;
}

pub struct DefaultSetupGenerator;

impl SetupGenerator for DefaultSetupGenerator {
    fn generate_config_toml(
        &self,
        config: &OmxConfig,
        _scope: SetupScope,
    ) -> Result<String, OmxError> {
        let mut out = String::new();
        out.push_str("# OMX:START — managed by omx setup, do not edit\n\n");
        out.push_str(&format!("model = \"{}\"\n\n", config.models.frontier));
        let servers = [
            ("omx_state", "omx-mcp-state"),
            ("omx_memory", "omx-mcp-memory"),
            ("omx_code_intel", "omx-mcp-code-intel"),
            ("omx_trace", "omx-mcp-trace"),
            ("omx_team", "omx-mcp-team"),
        ];
        for (name, binary) in servers {
            out.push_str(&format!("[mcp_servers.{name}]\n"));
            out.push_str(&format!("command = \"{binary}\"\n"));
            out.push_str("args = []\n");
            out.push_str("enabled = true\n");
            out.push_str("startup_timeout_sec = 5\n\n");
        }
        out.push_str("# OMX:END\n");
        Ok(out)
    }

    fn generate_agents_md(&self, config: &OmxConfig) -> Result<String, OmxError> {
        let mut out = String::new();
        out.push_str("# AGENTS\n\n");
        out.push_str("> Auto-generated by `omx setup`. Do not edit manually.\n\n");
        out.push_str("## Model defaults\n\n");
        out.push_str(&format!("- **Frontier:** {}\n", config.models.frontier));
        out.push_str(&format!("- **Standard:** {}\n", config.models.standard));
        out.push_str(&format!("- **Spark:** {}\n\n", config.models.spark));
        out.push_str("## Delegation rules\n\n");
        out.push_str("- Task delegation is driven by AGENTS.md injection at launch.\n");
        out.push_str("- Each agent has a role prompt in `prompts/<name>.md`.\n");
        out.push_str("- Agent config is in `agents/<name>.toml`.\n");
        out.push_str("- MCP servers are registered in `config.toml` under `[mcp_servers]`.\n");
        Ok(out)
    }

    fn generate_agent_tomls(
        &self,
        agents: &[AgentDefinition],
    ) -> Result<Vec<(String, String)>, OmxError> {
        let mut files = Vec::with_capacity(agents.len());
        for agent in agents {
            let filename = format!("{}.toml", agent.name);
            let mut content = String::new();
            content.push_str(&format!("name = \"{}\"\n", agent.name));
            content.push_str(&format!("description = \"{}\"\n", agent.description));
            if let Some(model) = &agent.model {
                content.push_str(&format!("model = \"{model}\"\n"));
            }
            if !agent.tools.is_empty() {
                let tools_str: Vec<String> =
                    agent.tools.iter().map(|t| format!("\"{t}\"")).collect();
                content.push_str(&format!("tools = [{}]\n", tools_str.join(", ")));
            }
            files.push((filename, content));
        }
        Ok(files)
    }

    fn sync_mcp_servers(&self, config: &OmxConfig, scope: SetupScope) -> Result<(), OmxError> {
        let config_path = match scope {
            SetupScope::User => config.codex_home.join("config.toml"),
            SetupScope::Project => std::env::current_dir()
                .map_err(OmxError::Io)?
                .join(".omx")
                .join("config.toml"),
        };

        let omx_section = self.generate_config_toml(config, scope)?;

        let existing = if config_path.exists() {
            std::fs::read_to_string(&config_path).map_err(OmxError::Io)?
        } else {
            String::new()
        };

        let new_content = if existing.contains("# OMX:START") && existing.contains("# OMX:END") {
            let start = existing.find("# OMX:START").unwrap();
            let end = existing.find("# OMX:END").unwrap() + "# OMX:END".len();
            let end = if existing[end..].starts_with('\n') {
                end + 1
            } else {
                end
            };
            format!("{}{}{}", &existing[..start], omx_section, &existing[end..])
        } else if existing.is_empty() {
            omx_section
        } else {
            format!("{}\n{}", existing.trim_end(), omx_section)
        };

        if let Some(parent) = config_path.parent() {
            std::fs::create_dir_all(parent).map_err(OmxError::Io)?;
        }
        std::fs::write(&config_path, new_content).map_err(OmxError::Io)?;
        Ok(())
    }

    fn copy_prompts(&self, _scope: SetupScope) -> Result<(), OmxError> {
        todo!("Phase 4: write embedded prompts to disk")
    }

    fn copy_skills(&self, _scope: SetupScope) -> Result<(), OmxError> {
        todo!("Phase 4: write embedded skills to disk")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn setup_scope_serde_roundtrip() {
        let scope = SetupScope::Project;
        let json = serde_json::to_string(&scope).unwrap();
        let parsed: SetupScope = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, scope);
    }

    #[test]
    fn generate_config_toml_has_markers_and_mcp_entries() {
        let gen = DefaultSetupGenerator;
        let config = OmxConfig::default();
        let result = gen.generate_config_toml(&config, SetupScope::User).unwrap();
        assert!(result.contains("# OMX:START"), "must have start marker");
        assert!(result.contains("# OMX:END"), "must have end marker");
        assert!(
            result.contains("[mcp_servers.omx_state]"),
            "must register omx-mcp-state"
        );
        assert!(
            result.contains("[mcp_servers.omx_memory]"),
            "must register omx-mcp-memory"
        );
        assert!(
            result.contains("[mcp_servers.omx_code_intel]"),
            "must register omx-mcp-code-intel"
        );
        assert!(
            result.contains("[mcp_servers.omx_trace]"),
            "must register omx-mcp-trace"
        );
        assert!(
            result.contains("[mcp_servers.omx_team]"),
            "must register omx-mcp-team"
        );
        assert!(
            result.contains("command = \"omx-mcp-state\""),
            "must use binary name"
        );
    }

    #[test]
    fn sync_mcp_servers_writes_config_file() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = OmxConfig::default();
        config.codex_home = dir.path().to_path_buf();

        let gen = DefaultSetupGenerator;
        gen.sync_mcp_servers(&config, SetupScope::User).unwrap();

        let config_path = dir.path().join("config.toml");
        assert!(config_path.exists(), "config.toml must be created");
        let contents = std::fs::read_to_string(&config_path).unwrap();
        assert!(contents.contains("# OMX:START"));
        assert!(contents.contains("[mcp_servers.omx_state]"));
    }

    #[test]
    fn sync_mcp_servers_preserves_user_content() {
        let dir = tempfile::tempdir().unwrap();
        let config_path = dir.path().join("config.toml");
        std::fs::write(
            &config_path,
            "# My custom setting\nmy_key = \"my_value\"\n\n# OMX:START\nold stuff\n# OMX:END\n\n# More custom\n",
        )
        .unwrap();

        let mut config = OmxConfig::default();
        config.codex_home = dir.path().to_path_buf();

        let gen = DefaultSetupGenerator;
        gen.sync_mcp_servers(&config, SetupScope::User).unwrap();

        let contents = std::fs::read_to_string(&config_path).unwrap();
        assert!(
            contents.contains("my_key = \"my_value\""),
            "user content preserved before markers"
        );
        assert!(
            contents.contains("# More custom"),
            "user content preserved after markers"
        );
        assert!(
            contents.contains("[mcp_servers.omx_state]"),
            "new OMX content injected"
        );
        assert!(!contents.contains("old stuff"), "old OMX content replaced");
    }

    #[test]
    fn generate_agent_tomls_produces_files() {
        let gen = DefaultSetupGenerator;
        let agents = vec![
            AgentDefinition {
                name: "architect".into(),
                description: "System design agent".into(),
                model: Some("o3".into()),
                tools: vec!["read".into(), "write".into()],
            },
            AgentDefinition {
                name: "reviewer".into(),
                description: "Code review agent".into(),
                model: None,
                tools: vec!["read".into()],
            },
        ];
        let result = gen.generate_agent_tomls(&agents).unwrap();
        assert_eq!(result.len(), 2);
        assert_eq!(result[0].0, "architect.toml");
        assert!(result[0].1.contains("name = \"architect\""));
        assert!(result[0].1.contains("model = \"o3\""));
        assert_eq!(result[1].0, "reviewer.toml");
        assert!(!result[1].1.contains("model ="), "no model when None");
    }

    #[test]
    fn generate_agents_md_has_header_and_delegation() {
        let gen = DefaultSetupGenerator;
        let config = OmxConfig::default();
        let result = gen.generate_agents_md(&config).unwrap();
        assert!(result.contains("# AGENTS"), "must have header");
        assert!(result.contains("delegation"), "must mention delegation rules");
    }
}
